Repository encode/httpcore, pull requests merged in 2020-11, with the labels that each got.

#232 Fix 0.12.1 release date
  CHANGELOG.md
Labels: documentation

#205 Introduce Hypercorn as a local test server
  requirements.txt
  tests/async_tests/test_interfaces.py
  tests/conftest.py
  tests/sync_tests/test_interfaces.py
  tests/utils.py
Labels: refactor

#233 Use Hypercorn for UDS tests
  requirements.txt
  tests/async_tests/test_interfaces.py
  tests/conftest.py
  tests/sync_tests/test_interfaces.py
  tests/utils.py
Labels: refactor

#234 Fix flaky test
  tests/async_tests/test_retries.py
  tests/sync_tests/test_retries.py
Labels: refactor

#237 Fix import of HTTP/1.1 connection causing thread-safety bug on 3.9
  httpcore/_async/connection.py
  httpcore/_sync/connection.py
  tests/test_threadsafety.py
Labels: bug

#167 Abort SSL connections on close, rather than waiting for remote EOF.
  httpcore/_backends/asyncio.py
Labels: bug

#244 Tweak `is_readable` comment.
  httpcore/_backends/asyncio.py
Labels: documentation
