Repository encode/httpcore, pull requests merged in 2020-08, with the labels that each got.

#128 Add an `UnsupportedProtocol` exception
  httpcore/__init__.py
  httpcore/_async/connection_pool.py
  httpcore/_exceptions.py
  httpcore/_sync/connection_pool.py
  tests/async_tests/test_interfaces.py
  tests/sync_tests/test_interfaces.py
Labels: enhancement

#121 Optional HTTP/2
  httpcore/_async/connection.py
  httpcore/_async/http.py
  httpcore/_async/http11.py
  httpcore/_async/http2.py
  httpcore/_sync/connection.py
  httpcore/_sync/http.py
  httpcore/_sync/http11.py
  httpcore/_sync/http2.py
Labels: enhancement

#129 Add LocalProtocolError, RemoteProtocolError
  httpcore/__init__.py
  httpcore/_async/connection_pool.py
  httpcore/_async/http11.py
  httpcore/_async/http2.py
  httpcore/_exceptions.py
  httpcore/_sync/connection_pool.py
  httpcore/_sync/http11.py
  httpcore/_sync/http2.py
Labels: enhancement

#136 Improve performance when receiving large responses
  httpcore/_async/http11.py
  httpcore/_async/http2.py
  httpcore/_sync/http11.py
  httpcore/_sync/http2.py
Labels: enhancement

#134 Local address support
  httpcore/_async/connection.py
  httpcore/_async/connection_pool.py
  httpcore/_backends/asyncio.py
  httpcore/_backends/auto.py
  httpcore/_backends/base.py
  httpcore/_backends/sync.py
  httpcore/_backends/trio.py
  httpcore/_sync/connection.py
  httpcore/_sync/connection_pool.py
  tests/async_tests/test_interfaces.py
  tests/sync_tests/test_interfaces.py
Labels: enhancement

#130 Finalize optional HTTP/2
  README.md
  docs/index.md
  httpcore/_async/connection_pool.py
  httpcore/_sync/connection_pool.py
  requirements.txt
  setup.py
Labels: enhancement

#133 Pure ByteStream interface
  docs/api.md
  httpcore/__init__.py
  httpcore/_async/base.py
  httpcore/_async/http11.py
  httpcore/_async/http2.py
  httpcore/_bytestreams.py
  httpcore/_sync/base.py
  httpcore/_sync/http11.py
  httpcore/_sync/http2.py
  unasync.py
Labels: enhancement

#137 Tweak `get_connection_info()` and `keepalive_expiry` behaviour.
  httpcore/_async/connection_pool.py
  httpcore/_sync/connection_pool.py
  tests/async_tests/test_interfaces.py
  tests/sync_tests/test_interfaces.py
Labels: enhancement

#153 Fix max_keepalive_connections config
  httpcore/_async/connection_pool.py
  httpcore/_sync/connection_pool.py
  tests/async_tests/test_interfaces.py
  tests/conftest.py
  tests/sync_tests/test_interfaces.py
Labels: bug

#170 Making release() and time() async
  httpcore/_async/connection_pool.py
  httpcore/_async/http2.py
  httpcore/_backends/asyncio.py
  httpcore/_backends/auto.py
  httpcore/_backends/base.py
  httpcore/_backends/trio.py
Labels: refactor
