Repository encode/httpcore, pull requests merged in 2021-04, with the labels that each got.

#285 Migrate docs to Sphinx + MyST
  docs/api.md
  docs/conf.py
  docs/contributing.md
  docs/css/custom.css
  docs/index.md
  httpcore/__init__.py
  httpcore/_async/base.py
  httpcore/_async/connection_pool.py
  httpcore/_async/http_proxy.py
  httpcore/_bytestreams.py
  httpcore/_sync/base.py
  httpcore/_sync/connection_pool.py
  httpcore/_sync/http_proxy.py
  mkdocs.yml
  requirements.txt
  scripts/build
  scripts/docs
  scripts/publish
Labels: documentation

#310 Don't raise exceptions on graceless close cases
  httpcore/_backends/anyio.py
  httpcore/_backends/asyncio.py
  httpcore/_backends/sync.py
  httpcore/_backends/trio.py
Labels: bug

#311 More resiliant `is_readable` testing
  httpcore/_backends/anyio.py
  httpcore/_backends/asyncio.py
  httpcore/_backends/curio.py
  httpcore/_backends/sync.py
  httpcore/_utils.py
  tests/backend_tests/test_asyncio.py
Labels: refactor
