Repository encode/httpcore, pull requests merged in 2023-07, with the labels that each got.

#641 Handle HTTP/1.1 half-closed connections gracefully.
  httpcore/_async/http11.py
  httpcore/_sync/http11.py
  tests/_async/test_connection.py
  tests/_sync/test_connection.py
Labels: bug

#749 Update `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#752 Use `pyproject.toml` for packaging instead of `setup.py`
  MANIFEST.in
  pyproject.toml
  requirements.txt
  scripts/build
  setup.py
Labels: tooling
