Repository encode/httpcore, pull requests merged in 2023-05, with the labels that each got.

#682 Fix incorrect docstring in test case
  tests/_async/test_http2.py
  tests/_sync/test_http2.py
Labels: refactor

#688 Fix pool timeout edge-case.
  CHANGELOG.md
  httpcore/_async/connection_pool.py
  httpcore/_sync/connection_pool.py
  tests/_async/test_connection_pool.py
  tests/_sync/test_connection_pool.py
Labels: bug

#696 Add sni hostname extension
  CHANGELOG.md
  docs/extensions.md
  httpcore/_async/connection.py
  httpcore/_sync/connection.py
Labels: enhancement

#668 Add support for socket options
  CHANGELOG.md
  docs/connection-pools.md
  httpcore/_async/connection.py
  httpcore/_async/connection_pool.py
  httpcore/_async/http_proxy.py
  httpcore/_sync/connection.py
  httpcore/_sync/connection_pool.py
  httpcore/_sync/http_proxy.py
  httpcore/backends/asyncio.py
  httpcore/backends/auto.py
  httpcore/backends/base.py
  httpcore/backends/mock.py
  httpcore/backends/sync.py
  httpcore/backends/trio.py
  tests/_async/test_connection.py
  tests/_async/test_connection_pool.py
  tests/_async/test_http_proxy.py
  tests/_sync/test_connection.py
  tests/_sync/test_connection_pool.py
  tests/_sync/test_http_proxy.py
Labels: enhancement

#700 Add 'stream_id' to extensions documentation.
  docs/extensions.md
Labels: documentation
